project:
  type: website
  output-dir: docs

website:
  title: "harry_blog"
  navbar:
    left:
      - href: index.qmd
        text: Projects
      - text: Blog
        href: blog.qmd
      - text: About
        href: projects.qmd
      - text: Publication
        href: publication.qmd

format:
  html:
    theme: 
        light: theme.scss
        dark: theme-dark.scss
    css: styles.css
    toc: true



