project:
  type: website
  output-dir: docs

website:
  title: "harry_blog"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: 
        light: theme.scss
        dark: theme-dark.scss
    css: styles.css
    toc: true



